Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('membership')->group(function() {
//     Route::get('/', 'Admin\MembershipController@index');
// });

Route::middleware(['auth'])->group(function () {

    Route::prefix('manage')->group(function() {

        Route::prefix('members')->group(function() {

            Route::name('membership.')->group(function() {

                Route::get('dashboard', 'Admin\MembershipController@index')->name('dashboard');

                Route::get('index', 'Admin\MemberController@index')->name('index');
                Route::get('index/data', 'Admin\MemberController@indexData')->name('index.data');
                Route::get('detail', 'Admin\MemberController@show')->name('show');
                Route::delete('delete', 'Admin\MemberController@bulkDelete')->name('delete.bulk');

                /** Pemanggilan */
                Route::get('pemanggilan', 'Admin\PemanggilanController@index')->name('pemanggilan');
                Route::get('pemanggilan/data', 'Admin\PemanggilanController@indexData')->name('pemanggilan.data');
                Route::post('pemanggilan/proses-bulk', 'Admin\PemanggilanController@prosesBulk')->name('pemanggilan.proses.bulk');

                /** Konfirmasi Pemanggilan */
                Route::get('pemanggilan-konfirmasi', 'Admin\PemanggilanKonfirmasiController@index')->name('pemanggilan.konfirmasi');
                Route::get('pemanggilan-konfirmasi/data', 'Admin\PemanggilanKonfirmasiController@indexData')->name('pemanggilan.konfirmasi.data');

                /** Psikotest */
                Route::get('psikotest', 'Admin\PsikotestController@index')->name('psikotest');
                Route::get('psikotest/data', 'Admin\PsikotestController@indexData')->name('psikotest.data');

                /** Psikotest */
                Route::get('interview', 'Admin\InterviewController@index')->name('interview');
                Route::get('interview/data', 'Admin\InterviewController@indexData')->name('interview.data');

                /** Medical Check Up */
                Route::get('mcu', 'Admin\McuController@index')->name('mcu');
                Route::get('mcu/data', 'Admin\McuController@indexData')->name('mcu.data');

                /** Joined */
                Route::get('joined', 'Admin\JoinedController@index')->name('joined');
                Route::get('joined/data', 'Admin\JoinedController@indexData')->name('joined.data');

                /** Reports */
                Route::get('reports', 'Admin\ReportController@index')->name('report');

            });

        });

    });

});
Route::get('members/login', 'Members\Auth\LoginController@showLoginForm')->name('membership.login');
Route::post('members/login', 'Members\Auth\LoginController@login')->name('membership.login.submit');
Route::post('members/logout', 'Members\Auth\LoginController@logout')->name('membership.logout');
Route::post('members/register', 'Members\Auth\RegisterController@register')->name('membership.register.submit');
Route::get('members/register/success', 'Members\Auth\RegisterController@registerSuccess')->name('membership.register.success');
Route::get('members/email/verify/{id}', 'Members\Auth\RegisterController@verifyEmail')->name('membership.email.verify');
Route::get('members/email/verify/success/{id}/{status}', 'Members\Auth\RegisterController@verifyEmailSuccess')->name('membership.email.verify.success');

Route::post('members/payment/notification', 'Members\PaymentController@notification')->name('payment.notification');
Route::get('members/payment/completed', 'Members\PaymentController@completed')->name('payment.completed');
Route::get('members/payment/failed', 'Members\PaymentController@failed')->name('payment.failed');
Route::get('members/payment/unfinished', 'Members\PaymentController@unfinished')->name('payment.unfinished');

Route::middleware(['auth:member'])->group(function () {

    Route::prefix('members')->group(function() {

        Route::name('membership.')->group(function() {
            
            Route::get('/', 'Members\HomeController@membersIndex');
            Route::get('home', 'Members\HomeController@index')->name('home');
            Route::get('profile', 'Members\HomeController@profile')->name('profile');
            Route::get('account', 'Members\HomeController@account')->name('account');
            Route::get('personal', 'Members\HomeController@personal')->name('personal');
            Route::get('education', 'Members\HomeController@education')->name('education');
            Route::get('experiences', 'Members\HomeController@experiences')->name('experiences');
            Route::get('address', 'Members\HomeController@address')->name('address');

            /** Wizard Biodata */
            Route::get('biodata/check', 'Members\HomeController@biodatacheck')->name('biodata.check');
            Route::get('biodata/wizard', 'Members\HomeController@biodataWizard')->name('biodata.wizard');
            Route::get('biodata/personal', 'Members\HomeController@wizardPersonal')->name('biodata.personal');
            Route::post('biodata/personal', 'Members\HomeController@wizardPersonalSave')->name('biodata.personal.save');
            Route::get('biodata/address', 'Members\HomeController@wizardAddress')->name('biodata.address');
            Route::post('biodata/address', 'Members\HomeController@wizardAddressSave')->name('biodata.address.save');
            Route::get('biodata/emergency', 'Members\HomeController@wizardEmergency')->name('biodata.emergency');
            Route::post('biodata/emergency', 'Members\HomeController@wizardEmergencySave')->name('biodata.emergency.save');
            Route::get('biodata/education', 'Members\HomeController@wizardEducation')->name('biodata.education');
            Route::post('biodata/education', 'Members\HomeController@wizardEducationSave')->name('biodata.education.save');
            Route::get('biodata/experience', 'Members\HomeController@wizardExperience')->name('biodata.experience');
            Route::post('biodata/experience', 'Members\HomeController@wizardExperienceSave')->name('biodata.experience.save');
            Route::get('biodata/document', 'Members\HomeController@wizardDocument')->name('biodata.document');
            Route::post('biodata/document', 'Members\HomeController@wizardDocumentSave')->name('biodata.document.save');

            /* Upload File */
            Route::post('biodata/upload', 'Members\HomeController@upload')->name('biodata.upload');

            /* Recruitment */
            Route::get('recruitment', 'Members\RecruitmentController@index')->name('recruitment');
            Route::get('recruitment/pemanggilan', 'Members\RecruitmentController@pemanggilan')->name('rec.pemanggilan');
            Route::post('recruitment/pemanggilan/konfirmasi', 'Members\RecruitmentController@pemanggilanConfirm')->name('rec.pemanggilan.konfirmasi');
            Route::post('recruitment/pemanggilan/reject', 'Members\RecruitmentController@pemanggilanReject')->name('rec.pemanggilan.reject');

            /** Payment */
            Route::get('payment/order', 'Members\PaymentController@order')->name('payment.order');
            Route::post('payment/order/save', 'Members\PaymentController@orderSave')->name('payment.order.save');

            /* Test */
            // Route::get('payment/test', 'Members\PaymentController@testSendEmail')->name('payment.test');

        });
    });
});

Entities/MemberType.php
<?php

namespace Modules\Membership\Entities;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuid as TraitsUuid;

class MemberType extends Model
{
    use TraitsUuid;

    protected $table = 'mbr_types';

    protected $fillable = [
        'code',
        'name',
        'description',
        'amount',
        'is_active',
        'created_by',
        'updated_by'
    ];

    public static function getMemberTypeForDropdownList($status = null)
    {
        if($status != null) {
            return self::where('is_active', $status)->pluck('name', 'code');
        } else {
            return self::pluck('name', 'code');
        }
    }

    public const MEMBER_FREE = "FREE";
    public const MEMBER_PRO = "PRO";
}

Http/Controllers/Admin/MemberController.php
<?php

namespace Modules\Membership\Http\Controllers\Admin;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Yajra\DataTables\Facades\DataTables;
use Modules\Membership\Entities\Members;
use Modules\Membership\Entities\View\MemberAvailableView;

class MemberController extends Controller
{
    protected $pageTitle;

    public function __construct()
    {
        $this->pageTitle = 'Members';
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        return view('membership::admin.members.index', $params);
    }

    public function indexData(Request $request)
    {
        if($request->ajax()) {
            $data = new MemberAvailableView();
            if(isset($request->start_date)) {
                $data = $data->whereDate('created_at', '>=', dateFormatYmd($request->start_date));
            } else {
                $data = $data->whereDate('created_at', '>=', Carbon::now()->subDays(1));
            }
            if(isset($request->end_date)) {
                $data = $data->whereDate('created_at', '<=', dateFormatYmd($request->end_date));
            } else {
                $data = $data->whereDate('created_at', '<=', Carbon::now());
            }
            $data = $data->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('checkboxes', function($row) {
                    return null;
                })
                ->addColumn('action', function($row) {
                    $actionBtn = 
                    '
                    <div class="btn-group">
                        <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Action</span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <li>
                                <a href="#" onclick="getDetail(\''.$row->id.'\');return false;"><i class="fa fa-eye"></i>Detail</a>
                            </li>
                        </ul>
                    </div>
                    ';
                    return $actionBtn;
                })
                ->rawColumns([
                    'action',
                ])
                ->make(true);
        }
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show(Request $request)
    {
        $id = $request->id;
        $params['data']         = Members::findOrFail($id);
        return view('membership::admin.members.show', $params);
    }

    public function bulkDelete(Request $request)
    {
        try {
            $ids = $request->id;
            foreach ($ids as $id) {
                Members::findOrFail($id)->delete();
            }
            return response()->json([
                'message' => 'Data berhasil dihapus.'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'message' => $e
            ]);
        }
    }
}

Http/Controllers/Members/RecruitmentController.php
<?php

namespace Modules\Membership\Http\Controllers\Members;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Modules\Membership\Entities\Members;
use Modules\Membership\Entities\Pemanggilan;

class RecruitmentController extends Controller
{
    protected $pageTitle;

    public function __construct()
    {
        $this->pageTitle = 'Recruitment';
    }

    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        $id = Auth::user()->id;
        $params['data']         = $data = Members::findOrFail($id);
        $params['alamatDom']    = $data->hasAddress->where('type', 'dom')->first();
        return view('membership::members.recruitment.index', $params);
    }

    public function pemanggilan(Request $request)
    {
        $userID = Auth::user()->id;
        $params['data'] = Pemanggilan::where('member_id', $userID)
            ->orderBy('created_at', 'DESC')
            ->get();
        return view('membership::members.recruitment.pemanggilan', $params);
    }

    public function pemanggilanForm(Request $request)
    {
        $params['data'] = Pemanggilan::findOrFail($request->id);
        return view('membership::members.recruitment.modals.confirmation', $params);
    }

    public function pemanggilanConfirm(Request $request)
    {
        try {
            $note = $request->note;
            $id = $request->id;
            Pemanggilan::where('id', $id)->update([
                'status' => Pemanggilan::STATUS_CONFIRMED,
                'confirmed_at' => Carbon::now(),
                'note' => $note
            ]);

            return response()->json([
                'code' => 200,
                'message' => 'Berhasil melakukan konfirmasi'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'code' => 200,
                'message' => 'Gagal melakukan konfirmasi' . $e
            ]);
        }
    }

    public function pemanggilanReject(Request $request)
    {
        try {
            $note = $request->note;
            $id = $request->id;
            $pemanggilan = Pemanggilan::findOrFail('id', $id);
            $pemanggilan->update([
                'status' => Pemanggilan::STATUS_REJECTED,
                'confirmed_at' => Carbon::now(),
                'note' => $note
            ]);
            Members::findOrFail($pemanggilan->member_id)
                ->update([
                    'rec_status' => Members::REC_STATUS_AVAILABLE
                ]);

            return response()->json([
                'code' => 200,
                'message' => 'Berhasil menolak panggilan'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'code' => 200,
                'message' => 'Gagal menolak panggilan' . $e
            ]);
        }
    }
}

Resources/views/members/biodata/wizard-1.blade.php
@extends('membership::members.layouts.app')

@section('content')

    @include('membership::members.biodata.wizard-warning')
    @include('membership::members.biodata.wizard-step')

    <div class="d-flex flex-column-fluid">
        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <div class="card card-custom gutter-b example example-compact">
                        <div class="card-header">
                            <h3 class="card-title">Data Pribadi</h3>
                        </div>
                        <form action="{!! route('membership.biodata.personal.save') !!}" method="POST" id="form_wizard_1" autocomplete="off">
                            @csrf
                            <div class="card-body">
                                
                                @include('membership::members.biodata.wizard-alert')

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label for="full_name" class="col-4 col-form-label">Nama Depan <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::text('full_name', $data->full_name, ['class' => 'form-control text-uppercase', 'id' => 'full_name', 'required']) !!}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="b_place" class="col-4 col-form-label">Tempat Lahir <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::text('b_place', isset($data->hasData->b_place) ? $data->hasData->b_place : null, ['class' => 'form-control text-uppercase', 'id' => 'b_place', 'required']) !!}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="b_date" class="col-4 col-form-label">Tgl. Lahir <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::date('b_date', isset($data->hasData->b_date) ? $data->hasData->b_date : null, ['class' => 'form-control', 'id' => 'b_date', 'required']) !!}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-4 col-form-label">Jenis Kelamin <span class="text-danger">*</span></label>
                                            <div class="col-8 col-form-label">
                                                <div class="radio-inline">
                                                    <label class="radio">
                                                        <input type="radio" name="gender" value="L" @if(isset($data->hasData->gender) && $data->hasData->gender == 'L') checked @endif /> 
                                                        <span></span> Laki-Laki
                                                    </label>
                                                    <label class="radio">
                                                        <input type="radio" name="gender" value="P" @if(isset($data->hasData->gender) && $data->hasData->gender == 'P') checked @endif />
                                                        <span></span> Perempuan
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="bb" class="col-4 col-form-label">Berat Badan <span class="text-danger">*</span></label>
                                            <div class="col-4">
                                                {!! Form::number('bb', isset($data->hasData->bb) ? $data->hasData->bb : null, ['class' => 'form-control text-right', 'id' => 'bb']) !!}
                                            </div>
                                            <label class="col-2 col-form-label">kg</label>
                                        </div>
                                        <div class="form-group row">
                                            <label for="tb" class="col-4 col-form-label">Tinggi Badan <span class="text-danger">*</span></label>
                                            <div class="col-4">
                                                {!! Form::number('tb', isset($data->hasData->tb) ? $data->hasData->tb : null, ['class' => 'form-control text-right', 'id' => 'tb']) !!}
                                            </div>
                                            <label class="col-2 col-form-label">cm</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label for="nik" class="col-4 col-form-label">NIK <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::text('nik', isset($data->hasData->nik) ? $data->hasData->nik : null, ['class' => 'form-control', 'id' => 'nik', 'maxlength' => 16]) !!}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="no_hp" class="col-4 col-form-label">No. HP <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::text('no_hp', isset($data->hasData->phone) ? $data->hasData->phone : null, ['class' => 'form-control', 'id' => 'no_hp']) !!}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="no_wa" class="col-4 col-form-label">No. WA <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::text('no_wa', isset($data->hasData->wa) ? $data->hasData->wa : null, ['class' => 'form-control', 'id' => 'no_wa']) !!}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="marital" class="col-4 col-form-label">Status Perkawinan <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::select('marital', $marital, isset($data->hasData->marital_id) ? $data->hasData->marital_id : null, [ 'class' => 'form-control text-uppercase selectpicker', 'id' => 'marital', 'placeholder' => 'Pilih']) !!}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-2"></div>
                                    <div class="col-10">
                                        <button type="submit" class="btn btn-success mr-2">Simpan & Lanjut</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

@section('css')
    <link href="{!! asset('modules/membership/theme/css/pages/wizard/wizard-1.css') !!}" rel="stylesheet" type="text/css" />
@endsection

@section('js')
    <script src="{!! asset('modules/membership/theme/js/pages/crud/forms/validation/biodata-wizard.js') !!}" type="text/javascript"></script>
@endsection

Resources/views/members/biodata/wizard-4.blade.php
@extends('membership::members.layouts.app')

@section('content')

    @include('membership::members.biodata.wizard-warning')
    @include('membership::members.biodata.wizard-step')

    <div class="d-flex flex-column-fluid">
        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <div class="card card-custom gutter-b example example-compact">
                        <div class="card-header">
                            <h3 class="card-title">Pendidikan Teakhir</h3>
                        </div>
                        <form action="{!! route('membership.biodata.education.save') !!}" method="POST" id="form_wizard_4" autocomplete="off">
                            @csrf
                            <div class="card-body">
                                
                                @include('membership::members.biodata.wizard-alert')

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label for="degree" class="col-4 col-form-label">Tingkat Pendidikan <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::select('degree', $degree, null, [ 'class' => 'form-control selectpicker', 'id' => 'degree', 'data-size' => 5, 'data-live-search' => 'true', 'placeholder' => 'Pilih', 'required']) !!}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="institution" class="col-4 col-form-label">Universitas/Sekolah <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::text('institution', null, ['class' => 'form-control text-uppercase', 'id' => 'institution', 'maxlength' => 50, 'required']) !!}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label for="majors" class="col-4 col-form-label">Jurusan <span class="text-danger">*</span></label>
                                            <div class="col-8">
                                                {!! Form::text('majors', null, ['class' => 'form-control text-uppercase', 'id' => 'majors', 'required']) !!}
                                            </div>
                                        </div>
                                        {{-- <div class="form-group row">
                                            <label for="start_year" class="col-4 col-form-label">Tahun Masuk <span class="text-danger">*</span></label>
                                            <div class="col-4">
                                                {!! Form::text('start_year', null, ['class' => 'form-control', 'id' => 'start_year', 'maxlength' => 4, 'required']) !!}
                                            </div>
                                        </div> --}}
                                        <div class="form-group row">
                                            <label for="graduation" class="col-4 col-form-label">Tahun Lulus</label>
                                            <div class="col-4">
                                                {!! Form::text('graduation', null, ['class' => 'form-control', 'id' => 'graduation', 'maxlength' => 4]) !!}
                                            </div>
                                        </div>
                                        {{-- <div class="form-group row">
                                            <label for="grade" class="col-4 col-form-label">IPK</label>
                                            <div class="col-4">
                                                {!! Form::text('grade', null, ['class' => 'form-control', 'id' => 'grade']) !!}
                                            </div>
                                        </div> --}}
                                        {{-- <div class="form-group row">
                                            <label for="note" class="col-4 col-form-label">Keterangan</label>
                                            <div class="col-8">
                                                {!! Form::textarea('note', null, ['class' => 'form-control', 'id' => 'note', 'rows' => 4]) !!}
                                            </div>
                                        </div> --}}
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-2"></div>
                                    <div class="col-10">
                                        <button type="submit" class="btn btn-success mr-2">Simpan & Lanjut</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('css')
    <link href="{!! asset('modules/membership/theme/css/pages/wizard/wizard-1.css') !!}" rel="stylesheet" type="text/css" />
@endsection

@section('js')
    <script src="{!! asset('modules/membership/theme/js/pages/crud/forms/validation/biodata-wizard-4.js') !!}" type="text/javascript"></script>
    {{-- <script>
        // $(document).ready(function() {
            // var provinsi = $("#provinsi");
            // var kabupaten = $("#kabupaten");
            // var placeHolder = '<option value="">Pilih</option>';
            // provinsi.on('change', function(e) {
            //     e.preventDefault();
            //     let provId = e.target.value;
            //     if(provId !== '') {
            //         $.ajax({
            //             url: "{!! route('kabupaten.list') !!}",
            //             type: "GET",
            //             data: { prov_id: provId },
            //             success: function (data) {
            //                 kabupaten.empty().append(placeHolder);
            //                 $.each(data, function(index, kab) {
            //                     kabupaten.append('<option value="' + kab.code + '">' + kab.name + '</option>').selectpicker('refresh');
            //                 });
            //             }
            //         });
            //     } else {
            //         kabupaten.empty().append(placeHolder).selectpicker('refresh');
            //     }
            // });
            
        // });
    </script> --}}
@endsection

Resources/views/members/biodata/wizard-alert.blade.php
@if (session('error'))
<div class="form-group mb-8">
    <div class="alert alert-custom alert-outline-danger fade show mb-5" role="alert">
        <div class="alert-icon">
            <i class="flaticon-warning"></i>
        </div>
        <div class="alert-text">{!! session('error') !!}</div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">
                    <i class="ki ki-close"></i>
                </span>
            </button>
        </div>
    </div>
</div>
@endif