Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('membership')->group(function() {
//     Route::get('/', 'Admin\MembershipController@index');
// });

Route::middleware(['auth'])->group(function () {

    Route::prefix('manage')->group(function() {

        Route::prefix('members')->group(function() {

            Route::name('membership.')->group(function() {

                Route::get('dashboard', 'Admin\MembershipController@index')->name('dashboard');

                Route::get('index', 'Admin\MemberController@index')->name('index');
                Route::get('index/data', 'Admin\MemberController@indexData')->name('index.data');
                Route::get('detail', 'Admin\MemberController@show')->name('show');
                Route::delete('delete', 'Admin\MemberController@bulkDelete')->name('delete.bulk');

                /** Pemanggilan */
                Route::get('pemanggilan', 'Admin\PemanggilanController@index')->name('pemanggilan');
                Route::get('pemanggilan/data', 'Admin\PemanggilanController@indexData')->name('pemanggilan.data');
                Route::post('pemanggilan/proses-bulk', 'Admin\PemanggilanController@prosesBulk')->name('pemanggilan.proses.bulk');

                /** Konfirmasi Pemanggilan */
                Route::get('pemanggilan-konfirmasi', 'Admin\PemanggilanKonfirmasiController@index')->name('pemanggilan.konfirmasi');
                Route::get('pemanggilan-konfirmasi/data', 'Admin\PemanggilanKonfirmasiController@indexData')->name('pemanggilan.konfirmasi.data');

                /** Psikotest */
                Route::get('psikotest', 'Admin\PsikotestController@index')->name('psikotest');
                Route::get('psikotest/data', 'Admin\PsikotestController@indexData')->name('psikotest.data');

                /** Psikotest */
                Route::get('interview', 'Admin\InterviewController@index')->name('interview');
                Route::get('interview/data', 'Admin\InterviewController@indexData')->name('interview.data');

                /** Medical Check Up */
                Route::get('mcu', 'Admin\McuController@index')->name('mcu');
                Route::get('mcu/data', 'Admin\McuController@indexData')->name('mcu.data');

                /** Joined */
                Route::get('joined', 'Admin\JoinedController@index')->name('joined');
                Route::get('joined/data', 'Admin\JoinedController@indexData')->name('joined.data');

                /** Reports */
                Route::get('reports', 'Admin\ReportController@index')->name('report');

            });

        });

    });

});
Route::get('members/login', 'Members\Auth\LoginController@showLoginForm')->name('membership.login');
Route::post('members/login', 'Members\Auth\LoginController@login')->name('membership.login.submit');
Route::post('members/logout', 'Members\Auth\LoginController@logout')->name('membership.logout');
Route::post('members/register', 'Members\Auth\RegisterController@register')->name('membership.register.submit');
Route::get('members/register/success', 'Members\Auth\RegisterController@registerSuccess')->name('membership.register.success');
Route::get('members/email/verify/{id}', 'Members\Auth\RegisterController@verifyEmail')->name('membership.email.verify');
Route::get('members/email/verify/success/{id}/{status}', 'Members\Auth\RegisterController@verifyEmailSuccess')->name('membership.email.verify.success');

Route::post('members/payment/notification', 'Members\PaymentController@notification')->name('payment.notification');
Route::get('members/payment/completed', 'Members\PaymentController@completed')->name('payment.completed');
Route::get('members/payment/failed', 'Members\PaymentController@failed')->name('payment.failed');
Route::get('members/payment/unfinished', 'Members\PaymentController@unfinished')->name('payment.unfinished');

Route::middleware(['auth:member'])->group(function () {

    Route::prefix('members')->group(function() {

        Route::name('membership.')->group(function() {
            
            Route::get('/', 'Members\HomeController@membersIndex');
            Route::get('home', 'Members\HomeController@index')->name('home');
            Route::get('profile', 'Members\HomeController@profile')->name('profile');
            Route::get('account', 'Members\HomeController@account')->name('account');
            Route::get('personal', 'Members\HomeController@personal')->name('personal');
            Route::get('education', 'Members\HomeController@education')->name('education');
            Route::get('experiences', 'Members\HomeController@experiences')->name('experiences');
            Route::get('address', 'Members\HomeController@address')->name('address');

            /** Wizard Biodata */
            Route::get('biodata/check', 'Members\HomeController@biodatacheck')->name('biodata.check');
            Route::get('biodata/wizard', 'Members\HomeController@biodataWizard')->name('biodata.wizard');
            Route::get('biodata/personal', 'Members\HomeController@wizardPersonal')->name('biodata.personal');
            Route::post('biodata/personal', 'Members\HomeController@wizardPersonalSave')->name('biodata.personal.save');
            Route::get('biodata/address', 'Members\HomeController@wizardAddress')->name('biodata.address');
            Route::post('biodata/address', 'Members\HomeController@wizardAddressSave')->name('biodata.address.save');
            Route::get('biodata/emergency', 'Members\HomeController@wizardEmergency')->name('biodata.emergency');
            Route::post('biodata/emergency', 'Members\HomeController@wizardEmergencySave')->name('biodata.emergency.save');
            Route::get('biodata/education', 'Members\HomeController@wizardEducation')->name('biodata.education');
            Route::post('biodata/education', 'Members\HomeController@wizardEducationSave')->name('biodata.education.save');
            Route::get('biodata/experience', 'Members\HomeController@wizardExperience')->name('biodata.experience');
            Route::post('biodata/experience', 'Members\HomeController@wizardExperienceSave')->name('biodata.experience.save');
            Route::get('biodata/document', 'Members\HomeController@wizardDocument')->name('biodata.document');
            Route::post('biodata/document', 'Members\HomeController@wizardDocumentSave')->name('biodata.document.save');

            /* Upload File */
            Route::post('biodata/upload', 'Members\HomeController@upload')->name('biodata.upload');

            /* Recruitment */
            Route::get('recruitment', 'Members\RecruitmentController@index')->name('recruitment');
            Route::get('recruitment/pemanggilan', 'Members\RecruitmentController@pemanggilan')->name('rec.pemanggilan');
            Route::post('recruitment/pemanggilan/konfirmasi', 'Members\RecruitmentController@pemanggilanConfirm')->name('rec.pemanggilan.konfirmasi');
            Route::post('recruitment/pemanggilan/reject', 'Members\RecruitmentController@pemanggilanReject')->name('rec.pemanggilan.reject');

            /** Payment */
            Route::get('payment/order', 'Members\PaymentController@order')->name('payment.order');
            Route::post('payment/order/save', 'Members\PaymentController@orderSave')->name('payment.order.save');

            /* Test */
            // Route::get('payment/test', 'Members\PaymentController@testSendEmail')->name('payment.test');

        });
    });
});

Entities/MemberType.php
<?php

namespace Modules\Membership\Entities;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuid as TraitsUuid;

class MemberType extends Model
{
    use TraitsUuid;

    protected $table = 'mbr_types';

    protected $fillable = [
        'code',
        'name',
        'description',
        'amount',
        'is_active',
        'created_by',
        'updated_by'
    ];

    public static function getMemberTypeForDropdownList($status = null)
    {
        if($status != null) {
            return self::where('is_active', $status)->pluck('name', 'code');
        } else {
            return self::pluck('name', 'code');
        }
    }

    public const MEMBER_FREE = "FREE";
    public const MEMBER_PRO = "PRO";
}

Http/Controllers/Admin/MemberController.php
<?php

namespace Modules\Membership\Http\Controllers\Admin;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Yajra\DataTables\Facades\DataTables;
use Modules\Membership\Entities\Members;
use Modules\Membership\Entities\View\MemberAvailableView;

class MemberController extends Controller
{
    protected $pageTitle;

    public function __construct()
    {
        $this->pageTitle = 'Members';
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        return view('membership::admin.members.index', $params);
    }

    public function indexData(Request $request)
    {
        if($request->ajax()) {
            $data = new MemberAvailableView();
            if(isset($request->start_date)) {
                $data = $data->whereDate('created_at', '>=', dateFormatYmd($request->start_date));
            } else {
                $data = $data->whereDate('created_at', '>=', Carbon::now()->subDays(1));
            }
            if(isset($request->end_date)) {
                $data = $data->whereDate('created_at', '<=', dateFormatYmd($request->end_date));
            } else {
                $data = $data->whereDate('created_at', '<=', Carbon::now());
            }
            $data = $data->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('checkboxes', function($row) {
                    return null;
                })
                ->addColumn('action', function($row) {
                    $actionBtn = 
                    '
                    <div class="btn-group">
                        <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Action</span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <li>
                                <a href="#" onclick="getDetail(\''.$row->id.'\');return false;"><i class="fa fa-eye"></i>Detail</a>
                            </li>
                        </ul>
                    </div>
                    ';
                    return $actionBtn;
                })
                ->rawColumns([
                    'action',
                ])
                ->make(true);
        }
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show(Request $request)
    {
        $id = $request->id;
        $params['data']         = Members::findOrFail($id);
        return view('membership::admin.members.show', $params);
    }

    public function bulkDelete(Request $request)
    {
        try {
            $ids = $request->id;
            foreach ($ids as $id) {
                Members::findOrFail($id)->delete();
            }
            return response()->json([
                'message' => 'Data berhasil dihapus.'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'message' => $e
            ]);
        }
    }
}

Http/Controllers/Members/RecruitmentController.php
<?php

namespace Modules\Membership\Http\Controllers\Members;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Modules\Membership\Entities\Members;
use Modules\Membership\Entities\Pemanggilan;

class RecruitmentController extends Controller
{
    protected $pageTitle;

    public function __construct()
    {
        $this->pageTitle = 'Recruitment';
    }

    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        $id = Auth::user()->id;
        $params['data']         = $data = Members::findOrFail($id);
        $params['alamatDom']    = $data->hasAddress->where('type', 'dom')->first();
        return view('membership::members.recruitment.index', $params);
    }

    public function pemanggilan(Request $request)
    {
        $userID = Auth::user()->id;
        $params['data'] = Pemanggilan::where('member_id', $userID)
            ->orderBy('created_at', 'DESC')
            ->get();
        return view('membership::members.recruitment.pemanggilan', $params);
    }

    public function pemanggilanForm(Request $request)
    {
        $params['data'] = Pemanggilan::findOrFail($request->id);
        return view('membership::members.recruitment.modals.confirmation', $params);
    }

    public function pemanggilanConfirm(Request $request)
    {
        try {
            $note = $request->note;
            $id = $request->id;
            Pemanggilan::where('id', $id)->update([
                'status' => Pemanggilan::STATUS_CONFIRMED,
                'confirmed_at' => Carbon::now(),
                'note' => $note
            ]);

            return response()->json([
                'code' => 200,
                'message' => 'Berhasil melakukan konfirmasi'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'code' => 200,
                'message' => 'Gagal melakukan konfirmasi' . $e
            ]);
        }
    }

    public function pemanggilanReject(Request $request)
    {
        try {
            $note = $request->note;
            $id = $request->id;
            $pemanggilan = Pemanggilan::findOrFail('id', $id);
            $pemanggilan->update([
                'status' => Pemanggilan::STATUS_REJECTED,
                'confirmed_at' => Carbon::now(),
                'note' => $note
            ]);
            Members::findOrFail($pemanggilan->member_id)
                ->update([
                    'rec_status' => Members::REC_STATUS_AVAILABLE
                ]);

            return response()->json([
                'code' => 200,
                'message' => 'Berhasil menolak panggilan'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'code' => 200,
                'message' => 'Gagal menolak panggilan' . $e
            ]);
        }
    }
}

Resources/views/admin/members/index.blade.php
@extends('membership::layouts.master')

@section('content')
    
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body" style="min-height: 520px">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-4 col-xs-6">
                                    <div class="form-group">
                                        <label for="start_date" class="small">Start Date</label>
                                        <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            {!! Form::text('start_date', date('d-m-Y'), [ 'class' => 'form-control datepicker input-sm', 'id' => 'start_date']) !!}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-xs-6">
                                    <div class="form-group">
                                        <label for="end_date" class="small">End Date</label>
                                        <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            {!! Form::text('end_date', date('d-m-Y'), [ 'class' => 'form-control datepicker input-sm', 'id' => 'end_date']) !!}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-xs-6">
                                    <div class="form-group">
                                        <label for="button" class="small"></label>
                                        <div class="input-group">
                                            <button class="btn btn-sm btn-success" style="margin-top: 4.5px" id="btn_search">
                                                <i class="fa fa-search"></i> Cari
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6"></div>
                    </div>
                    <hr>
                    <div class="row" style="margin-bottom: 10px">
                        <div class="col-md-12">
                            <button class="btn btn-xs btn-success hide" id="pemanggilan">
                                <i class="fa fa-forward"></i>
                                Proses Pemanggilan
                            </button>
                        </div>
                    </div>
                    <div class="divider"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table id="grid-members" class="table table-bordered table-striped" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th class="text-center" style="width: 2%">#</th>
                                            <th class="text-center" style="width: 5%">No. Member</th>
                                            <th class="text-center">NIK</th>
                                            <th class="text-center">Nama Lengkap</th>
                                            <th class="text-center">Email</th>
                                            <th class="text-center" style="width: 100px">Tgl. Daftar</th>
                                            <th class="text-center" style="width: 5%">
                                                <i class="fa fa-navicon"></i>
                                            </th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="detail" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="detail">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div id="content"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('css')
    <style>
        .datepicker table tr td.disabled{
            color:red;
            cursor: not-allowed;
        }
        .datepicker table tr td.today{
            background: orange;
        }
        .datepicker table tr td.active{
            font-weight: bold;
        }
    </style>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            var btnPemanggilan = $('#pemanggilan');
            var startDate = $('#start_date');
            var endDate = $('#end_date');
            var btnSearch = $('#btn_search');
            if(localStorage.getItem('mbr_start_date') !== null) {
                startDate.val(localStorage.getItem('mbr_start_date'));
            }
            if(localStorage.getItem('mbr_end_date') !== null) {
                endDate.val(localStorage.getItem('mbr_end_date'));
            }
            $('.datepicker').datepicker({
                format: 'dd-mm-yyyy',
                autoclose: true,
                todayHighlight: true,
                weekStart: 1,
                endDate: '+1d',
                language: 'id'
            });

            var table = $('#grid-members').DataTable({
                processing: true,
                serverSide: true,
                responsive: false,
                PaginationType: "two_button",
                paginate:true,
                deferRender: true,
                keys: false,
                scrollX: true,
                dom: '<"row"<"col-md-4"l><"col-md-4 text-center"B><"col-md-4"f>>' + 'rtip',
                select: {
                    style: 'os',
                    selector: 'td:first-child'
                },
                buttons: [
                    {
                        extend: 'selectAll',
                        text: 'Select All',
                        className: "btn-sm",
                    },
                    {
                        extend:'selectNone',
                        text: 'Select None',
                        className: "btn-sm",
                    },
                    {
                        text: '<i class="fa fa-refresh"></i> Refresh',
                        className: "btn-sm",
                        action: function(e, dt, node, config) {
                            dt.ajax.reload();
                            btnPemanggilan.addClass('hide');
                        }
                    }
                ],
                ajax: { 
                    url: "{!! route('membership.index.data') !!}",
                    pages: 10,
                    data: function(d) {
                        d.start_date = startDate.val();
                        d.end_date = endDate.val();
                    }
                },
                columns: [
                    {data: 'checkboxes', name: 'checkboxes', orderable: false, searchable: false},
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', className: "small", orderable: false, searchable: false},
                    {data: 'no_member', name: 'no_member', className: "small"},
                    {data: 'nik', name: 'nik', className: "small"},
                    {data: 'full_name', name: 'full_name', className: "small"},
                    {data: 'email', name: 'email', className: "small"},
                    {data: 'created_at', name: 'created_at', className: "small"},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ],
                columnDefs: [
                    {
                        targets: 0,
                        className: 'select-checkbox'
                    },
                    {targets: 6, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY HH:mm:ss' )},
                ],
                order: [
                    [6, 'desc']
                ],
                language: {
                    processing: "<p class='text-center'>Loading...</p>"
                },
            });

            table.on( 'select', function ( e, dt, type, indexes ) {
                var count = table.rows( { selected: true } ).count();
                if ( count > 0 ) {
                    btnPemanggilan.removeClass('hide');
                }
            } );

            table.on( 'deselect', function ( e, dt, type, indexes ) {
                var count = table.rows( { selected: true } ).count();
                if ( count === 0 ) {
                    btnPemanggilan.addClass('hide');
                }
            } );

            btnSearch.on('click', function(e) {
                e.preventDefault();
                getDataMember();
                localStorage.setItem('mbr_start_date', startDate.val());
                localStorage.setItem('mbr_end_date', endDate.val());
            });

            btnPemanggilan.on('click', function(e) {
                e.preventDefault();
                var countRows = table.rows( { selected: true } ).data().count();
                swal({
                    title: 'Konfirmasi',
                    text: 'Apakah kamu ingin melakukan pemanggilan pada ' + countRows + ' data ini?',
                    buttons: ["Batal", "Ya"],
                    dangerMode: true,
                    closeOnClickOutside: false,
                }).then(function(value) {
                    if(value) {
                        var selectedRows = table.rows( { selected: true } ).data().to$();
                        var selectedId = Array();
                        $.each(selectedRows, function(i, e) {
                            selectedId.push(e.id);
                        });
                        $.ajax({
                            url: "{!! route('membership.pemanggilan.proses.bulk') !!}",
                            type: "post",
                            data: {
                                _token: "{!! csrf_token() !!}",
                                id: selectedId,
                            },
                            success: function(res, stat, xhr) {
                                swal({
                                    text: res.message,
                                    icon: 'success',
                                    button: 'close',
                                    closeOnClickOutside: false,
                                });
                                table.draw();
                                btnPemanggilan.addClass('hide');
                            },
                            error: function(err) {
                                swal({
                                    text: err,
                                    icon: 'error',
                                    button: 'close',
                                    closeOnClickOutside: false,
                                });
                            }
                        });
                    }
                })
            });

            $('.dataTables_scrollBody').css('height', '350px');
            
            function getDataMember() {
                $.ajax({
                    url: "{!! route('membership.index.data') !!}",
                    type: "GET",
                    data: { 
                        start_date: startDate.val(),
                        end_date: endDate.val()
                    },
                    success: function(data) {
                        table.ajax.reload();
                    }
                });
            }
        });
        function getDetail(id) {
            $.ajax({
                type: "GET",
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{!! route('membership.show') !!}",
                data: {id: id},
                success: function(data) {
                    $('#detail').modal('toggle');
                    $('#content').html(data);
                }
            });
        }
    </script>
@endsection