Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('membership')->group(function() {
//     Route::get('/', 'Admin\MembershipController@index');
// });

Route::middleware(['auth'])->group(function () {

    Route::prefix('manage')->group(function() {

        Route::prefix('members')->group(function() {

            Route::name('membership.')->group(function() {

                Route::get('dashboard', 'Admin\MembershipController@index')->name('dashboard');

                Route::get('index', 'Admin\MemberController@index')->name('index');
                Route::get('index/data', 'Admin\MemberController@indexData')->name('index.data');
                Route::get('detail', 'Admin\MemberController@show')->name('show');
                Route::delete('delete', 'Admin\MemberController@bulkDelete')->name('delete.bulk');

                /** Pemanggilan */
                Route::get('pemanggilan', 'Admin\PemanggilanController@index')->name('pemanggilan');
                Route::get('pemanggilan/data', 'Admin\PemanggilanController@indexData')->name('pemanggilan.data');
                Route::post('pemanggilan/proses-bulk', 'Admin\PemanggilanController@prosesBulk')->name('pemanggilan.proses.bulk');

                /** Konfirmasi Pemanggilan */
                Route::get('pemanggilan-konfirmasi', 'Admin\PemanggilanKonfirmasiController@index')->name('pemanggilan.konfirmasi');
                Route::get('pemanggilan-konfirmasi/data', 'Admin\PemanggilanKonfirmasiController@indexData')->name('pemanggilan.konfirmasi.data');

                /** Psikotest */
                Route::get('psikotest', 'Admin\PsikotestController@index')->name('psikotest');
                Route::get('psikotest/data', 'Admin\PsikotestController@indexData')->name('psikotest.data');

                /** Psikotest */
                Route::get('interview', 'Admin\InterviewController@index')->name('interview');
                Route::get('interview/data', 'Admin\InterviewController@indexData')->name('interview.data');

                /** Medical Check Up */
                Route::get('mcu', 'Admin\McuController@index')->name('mcu');
                Route::get('mcu/data', 'Admin\McuController@indexData')->name('mcu.data');

                /** Joined */
                Route::get('joined', 'Admin\JoinedController@index')->name('joined');
                Route::get('joined/data', 'Admin\JoinedController@indexData')->name('joined.data');

                /** Reports */
                Route::get('reports', 'Admin\ReportController@index')->name('report');

            });

        });

    });

});
Route::get('members/login', 'Members\Auth\LoginController@showLoginForm')->name('membership.login');
Route::post('members/login', 'Members\Auth\LoginController@login')->name('membership.login.submit');
Route::post('members/logout', 'Members\Auth\LoginController@logout')->name('membership.logout');
Route::post('members/register', 'Members\Auth\RegisterController@register')->name('membership.register.submit');
Route::get('members/register/success', 'Members\Auth\RegisterController@registerSuccess')->name('membership.register.success');
Route::get('members/email/verify/{id}', 'Members\Auth\RegisterController@verifyEmail')->name('membership.email.verify');
Route::get('members/email/verify/success/{id}/{status}', 'Members\Auth\RegisterController@verifyEmailSuccess')->name('membership.email.verify.success');

Route::post('members/payment/notification', 'Members\PaymentController@notification')->name('payment.notification');
Route::get('members/payment/completed', 'Members\PaymentController@completed')->name('payment.completed');
Route::get('members/payment/failed', 'Members\PaymentController@failed')->name('payment.failed');
Route::get('members/payment/unfinished', 'Members\PaymentController@unfinished')->name('payment.unfinished');

Route::middleware(['auth:member'])->group(function () {

    Route::prefix('members')->group(function() {

        Route::name('membership.')->group(function() {
            
            Route::get('/', 'Members\HomeController@membersIndex');
            Route::get('home', 'Members\HomeController@index')->name('home');
            Route::get('profile', 'Members\HomeController@profile')->name('profile');
            Route::get('account', 'Members\HomeController@account')->name('account');
            Route::get('personal', 'Members\HomeController@personal')->name('personal');
            Route::get('education', 'Members\HomeController@education')->name('education');
            Route::get('experiences', 'Members\HomeController@experiences')->name('experiences');
            Route::get('address', 'Members\HomeController@address')->name('address');

            /** Wizard Biodata */
            Route::get('biodata/check', 'Members\HomeController@biodatacheck')->name('biodata.check');
            Route::get('biodata/wizard', 'Members\HomeController@biodataWizard')->name('biodata.wizard');
            Route::get('biodata/personal', 'Members\HomeController@wizardPersonal')->name('biodata.personal');
            Route::post('biodata/personal', 'Members\HomeController@wizardPersonalSave')->name('biodata.personal.save');
            Route::get('biodata/address', 'Members\HomeController@wizardAddress')->name('biodata.address');
            Route::post('biodata/address', 'Members\HomeController@wizardAddressSave')->name('biodata.address.save');
            Route::get('biodata/emergency', 'Members\HomeController@wizardEmergency')->name('biodata.emergency');
            Route::post('biodata/emergency', 'Members\HomeController@wizardEmergencySave')->name('biodata.emergency.save');
            Route::get('biodata/education', 'Members\HomeController@wizardEducation')->name('biodata.education');
            Route::post('biodata/education', 'Members\HomeController@wizardEducationSave')->name('biodata.education.save');
            Route::get('biodata/experience', 'Members\HomeController@wizardExperience')->name('biodata.experience');
            Route::post('biodata/experience', 'Members\HomeController@wizardExperienceSave')->name('biodata.experience.save');
            Route::get('biodata/document', 'Members\HomeController@wizardDocument')->name('biodata.document');
            Route::post('biodata/document', 'Members\HomeController@wizardDocumentSave')->name('biodata.document.save');

            /* Upload File */
            Route::post('biodata/upload', 'Members\HomeController@upload')->name('biodata.upload');

            /* Recruitment */
            Route::get('recruitment', 'Members\RecruitmentController@index')->name('recruitment');
            Route::get('recruitment/pemanggilan', 'Members\RecruitmentController@pemanggilan')->name('rec.pemanggilan');
            Route::post('recruitment/pemanggilan/konfirmasi', 'Members\RecruitmentController@pemanggilanConfirm')->name('rec.pemanggilan.konfirmasi');
            Route::post('recruitment/pemanggilan/reject', 'Members\RecruitmentController@pemanggilanReject')->name('rec.pemanggilan.reject');

            /** Payment */
            Route::get('payment/order', 'Members\PaymentController@order')->name('payment.order');
            Route::post('payment/order/save', 'Members\PaymentController@orderSave')->name('payment.order.save');

            /* Test */
            // Route::get('payment/test', 'Members\PaymentController@testSendEmail')->name('payment.test');

        });
    });
});

Entities/MemberType.php
<?php

namespace Modules\Membership\Entities;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuid as TraitsUuid;

class MemberType extends Model
{
    use TraitsUuid;

    protected $table = 'mbr_types';

    protected $fillable = [
        'code',
        'name',
        'description',
        'amount',
        'is_active',
        'created_by',
        'updated_by'
    ];

    public static function getMemberTypeForDropdownList($status = null)
    {
        if($status != null) {
            return self::where('is_active', $status)->pluck('name', 'code');
        } else {
            return self::pluck('name', 'code');
        }
    }

    public const MEMBER_FREE = "FREE";
    public const MEMBER_PRO = "PRO";
}

Http/Controllers/Admin/MemberController.php
<?php

namespace Modules\Membership\Http\Controllers\Admin;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Yajra\DataTables\Facades\DataTables;
use Modules\Membership\Entities\Members;
use Modules\Membership\Entities\View\MemberAvailableView;

class MemberController extends Controller
{
    protected $pageTitle;

    public function __construct()
    {
        $this->pageTitle = 'Members';
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        return view('membership::admin.members.index', $params);
    }

    public function indexData(Request $request)
    {
        if($request->ajax()) {
            $data = new MemberAvailableView();
            if(isset($request->start_date)) {
                $data = $data->whereDate('created_at', '>=', dateFormatYmd($request->start_date));
            } else {
                $data = $data->whereDate('created_at', '>=', Carbon::now()->subDays(1));
            }
            if(isset($request->end_date)) {
                $data = $data->whereDate('created_at', '<=', dateFormatYmd($request->end_date));
            } else {
                $data = $data->whereDate('created_at', '<=', Carbon::now());
            }
            $data = $data->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('checkboxes', function($row) {
                    return null;
                })
                ->addColumn('action', function($row) {
                    $actionBtn = 
                    '
                    <div class="btn-group">
                        <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Action</span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <li>
                                <a href="#" onclick="getDetail(\''.$row->id.'\');return false;"><i class="fa fa-eye"></i>Detail</a>
                            </li>
                        </ul>
                    </div>
                    ';
                    return $actionBtn;
                })
                ->rawColumns([
                    'action',
                ])
                ->make(true);
        }
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show(Request $request)
    {
        $id = $request->id;
        $params['data']         = Members::findOrFail($id);
        return view('membership::admin.members.show', $params);
    }

    public function bulkDelete(Request $request)
    {
        try {
            $ids = $request->id;
            foreach ($ids as $id) {
                Members::findOrFail($id)->delete();
            }
            return response()->json([
                'message' => 'Data berhasil dihapus.'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'message' => $e
            ]);
        }
    }
}

Http/Controllers/Members/RecruitmentController.php
<?php

namespace Modules\Membership\Http\Controllers\Members;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Modules\Membership\Entities\Members;
use Modules\Membership\Entities\Pemanggilan;

class RecruitmentController extends Controller
{
    protected $pageTitle;

    public function __construct()
    {
        $this->pageTitle = 'Recruitment';
    }

    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        $id = Auth::user()->id;
        $params['data']         = $data = Members::findOrFail($id);
        $params['alamatDom']    = $data->hasAddress->where('type', 'dom')->first();
        return view('membership::members.recruitment.index', $params);
    }

    public function pemanggilan(Request $request)
    {
        $userID = Auth::user()->id;
        $params['data'] = Pemanggilan::where('member_id', $userID)
            ->orderBy('created_at', 'DESC')
            ->get();
        return view('membership::members.recruitment.pemanggilan', $params);
    }

    public function pemanggilanForm(Request $request)
    {
        $params['data'] = Pemanggilan::findOrFail($request->id);
        return view('membership::members.recruitment.modals.confirmation', $params);
    }

    public function pemanggilanConfirm(Request $request)
    {
        try {
            $note = $request->note;
            $id = $request->id;
            Pemanggilan::where('id', $id)->update([
                'status' => Pemanggilan::STATUS_CONFIRMED,
                'confirmed_at' => Carbon::now(),
                'note' => $note
            ]);

            return response()->json([
                'code' => 200,
                'message' => 'Berhasil melakukan konfirmasi'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'code' => 200,
                'message' => 'Gagal melakukan konfirmasi' . $e
            ]);
        }
    }

    public function pemanggilanReject(Request $request)
    {
        try {
            $note = $request->note;
            $id = $request->id;
            $pemanggilan = Pemanggilan::findOrFail('id', $id);
            $pemanggilan->update([
                'status' => Pemanggilan::STATUS_REJECTED,
                'confirmed_at' => Carbon::now(),
                'note' => $note
            ]);
            Members::findOrFail($pemanggilan->member_id)
                ->update([
                    'rec_status' => Members::REC_STATUS_AVAILABLE
                ]);

            return response()->json([
                'code' => 200,
                'message' => 'Berhasil menolak panggilan'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'code' => 200,
                'message' => 'Gagal menolak panggilan' . $e
            ]);
        }
    }
}

Resources/views/members/recruitment/default.blade.php
{{-- <div id="data_content"> --}}
    <div class="flex-row-fluid ml-lg-8" id="data_content">
        <div class="card card-custom card-stretch">
            <div class="card-header py-3">
                <div class="card-title align-items-start flex-column">
                    <h3 class="card-label font-weight-bolder text-dark"></h3>
                    <span class="text-muted font-weight-bold font-size-sm mt-1"></span>
                </div>
            </div>
        </div>
    </div>
{{-- </div> --}}

Resources/views/members/recruitment/pemanggilan.blade.php
<div class="flex-row-fluid ml-lg-8" id="data_content">
    <div class="card card-custom card-stretch">
        <div class="card-header py-3">
            <div class="card-title align-items-start flex-column">
                <h3 class="card-label font-weight-bolder text-dark">Pemanggilan</h3>
                <span class="text-muted font-weight-bold font-size-sm mt-1"></span>
            </div>
            <div class="card-toolbar"></div>
        </div>
        <div class="card-body" style="min-height: 300px">
            <div class="table-responsive">
                <table class="table table-head-custom table-vertical-center table-head-bg table-borderless">
                    <thead>
                        <tr class="text-left">
                            <th style="min-width: 150px" class="pl-7">
                                <span class="text-dark-75">Tanggal Kirim</span>
                            </th>
                            <th style="min-width: 120px">Batas Waktu Konfirmasi</th>
                            <th style="min-width: 100px">Status</th>
                            <th style="min-width: 100px">Keterangan</th>
                            <th class="text-right" style="min-width: 80px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $row)
                        <tr>
                            <td>
                                <span class="text-dark-75 d-block font-size-sm">{!! dateFormatDmyHi($row->created_at) !!}</span>
                            </td>
                            <td>
                                <span class="text-dark-75 d-block font-size-sm">{!! dateFormatDmyHi($row->expired_at) !!}</span>
                            </td>
                            <td>
                                <span class="text-dark-75 d-block font-size-sm">
                                    {!! in_array($row->status, ['SENT', 'READ']) ? 'WAITING' : $row->status !!}
                                </span>
                            </td>
                            <td>
                                <span class="text-dark-75 d-block font-size-sm">{!! $row->note !!}</span>
                            </td>
                            <td class="pr-0 text-right">
                                @if(!in_array($row->status, ['CONFIRMED', 'REJECTED']))
                                <button class="btn btn-light-success font-weight-bolder font-size-sm" data-toggle="modal" data-target="#staticBackdrop">Konfirmasi</button>
                                @endif
                            </td>
                            <div class="modal fade" id="staticBackdrop" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Konfirmasi Pemanggilan</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <i aria-hidden="true" class="ki ki-close"></i>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="row">
                                                <div class="col-xl-12">
                                                    <span>Apakah kamu yakin ingin melakukan konfirmasi pemanggilan ? Jika ya Silahkan klik tombol Konfirmasi, jika tidak bersedia silahkan klik tombol Tolak dan isi alasan kamu.</span>
                                                    <br><br>
                                                    <div class="form-group">
                                                        <label>Alasan</label>
                                                        <textarea name="note" id="note" class="form-control form-control-md" maxlength="200" rows="5"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" onclick="confirmNow('{!! $row->id !!}')" class="btn btn-primary font-weight-bold">Konfirmasi</button>
                                            <button type="button" onclick="rejectNow('{!! $row->id !!}')" class="btn btn-danger font-weight-bold">Tolak</button>
                                            <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    function confirmNow(id) {
        var note = $("#note");
        var csrf = $('meta[name="csrf-token"]').attr('content');
        
        $.ajax({
            type: "POST",
            url: "{!! route('membership.rec.pemanggilan.konfirmasi') !!}",
            data: {
                id: id,
                note: note.val(),
                _token: csrf
            },
            success: function(data) {
                toastr.success(data.message);
                $("#staticBackdrop").modal('hide');
                $('#tab_pemanggilan').trigger( "click" );
            },
            error: function(xhr) {
                toastr.error(xhr.message);
            }
        });
    }
    function rejectNow(id) {
        var note = $("#note");
        var csrf = $('meta[name="csrf-token"]').attr('content');
        
        $.ajax({
            type: "POST",
            url: "{!! route('membership.rec.pemanggilan.reject') !!}",
            data: {
                id: id,
                note: note.val(),
                _token: csrf
            },
            success: function(data) {
                toastr.success(data.message);
                $("#staticBackdrop").modal('hide');
                $('#tab_pemanggilan').trigger( "click" );
            },
            error: function(xhr) {
                toastr.error(xhr.message);
            }
        });
    }
</script>